version: "3.8"
services:
  web:
    stdin_open: true
    image: femtasy-ta
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - "/app/node_modules"
      - "./:/app"

